#cloud-config
rancher:
  services:
    letsencrypt:
      image: quay.io/letsencrypt/letsencrypt:latest
      command: auth -m 45gedf@corngoodness.com -d 45gedf.corngoodness.com --agree-tos --test-cert
      ports:
        - 80:80
        - 443:443
      privileged: true
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/lib/letsencrypt:/var/lib/letsencrypt
